### ISSUE TITLE
How can you run your project successfully

### ISSUE THREAD

**Issue by uwkwi** [khdlr/deep-acm#1]
How do you find the data set and where to put it in order to successfully run your project

**Comment by khdlr** [comment]
Hi there, I recommend checking out the final version of this project at https://github.com/khdlr/cobra (Judging from your issue there, it seems you have already figured this out though... :wink:)

The steps to run the training script for this repo is the same though, Download the dataset from https://github.com/daniel-cheng/CALFIN and update `config.yml` to point to the downloaded data folder within the `CALFIN` repo. (cf. https://github.com/khdlr/COBRA/issues/2)
